'use strict';
(() => {
const D=A1_DATA,F=D.frames,EV=D.events,$=id=>document.getElementById(id);
const colors={blue:'#176f9b',orange:'#b96018',purple:'#755da3',gray:'#596b76',teal:'#2c8279',grid:'#e3e9ec'};
let index=0,eventId=null,playing=false,raf=0,playOrigin=0,wallOrigin=0;
const fmt=(v,p=6)=>v==null?'not recorded':Math.abs(v)>0&&Math.abs(v)<.0001?v.toExponential(3):Number(v).toFixed(p);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function table(rows){return '<table><tbody>'+rows.map(([a,b])=>`<tr><th>${esc(a)}</th><td>${esc(b)}</td></tr>`).join('')+'</tbody></table>';}
function floorTime(rows,time,key='time'){let lo=0,hi=rows.length;while(lo<hi){const m=(lo+hi)>>1;if(rows[m][key]<=time)lo=m+1;else hi=m;}return Math.max(0,lo-1);}
function selected(){const f=F[index],e=eventId===null?null:EV[eventId];return {f,e,time:e?e.time:f.time,position:e?e.position:f.position,angle:e?e.angle:f.angle,E:e?e.E:f.E,I:e?e.I:f.I,stock:e?e.stock:f.stock,contact:e?e.contact:f.contact,force:e?e.force:f.force};}
function pause(){playing=false;cancelAnimationFrame(raf);$('play').textContent='Play records';}
function setNative(i,stop=true){if(stop)pause();index=Math.max(0,Math.min(F.length-1,Number(i)));eventId=null;render();}
function setEvent(i){pause();eventId=Math.max(0,Math.min(EV.length-1,Number(i)));index=floorTime(F,EV[eventId].time);$('eventNumber').value=eventId;render();}
function setup(canvas){const rect=canvas.getBoundingClientRect(),w=Math.max(100,rect.width),h=Math.max(50,rect.height),dpr=window.devicePixelRatio||1;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);return [ctx,w,h];}
function plan(id,bounds,s){const [g,w,h]=setup($(id)),pad=32,scale=Math.min((w-2*pad)/(bounds[1]-bounds[0]),(h-2*pad)/(bounds[3]-bounds[2]));const ox=(w-scale*(bounds[1]-bounds[0]))/2,oy=(h-scale*(bounds[3]-bounds[2]))/2;const x=v=>ox+(v-bounds[0])*scale,y=v=>h-oy-(v-bounds[2])*scale;
g.font='11px Segoe UI';g.textAlign='center';g.fillStyle='#526775';
const tick=id==='arena'?5:1;for(let v=Math.ceil(bounds[0]/tick)*tick;v<=bounds[1];v+=tick){g.strokeStyle=colors.grid;g.beginPath();g.moveTo(x(v),y(bounds[2]));g.lineTo(x(v),y(bounds[3]));g.stroke();g.fillText(v,x(v),h-oy+17);}for(let v=Math.ceil(bounds[2]/tick)*tick;v<=bounds[3];v+=tick){g.strokeStyle=colors.grid;g.beginPath();g.moveTo(x(bounds[0]),y(v));g.lineTo(x(bounds[1]),y(v));g.stroke();g.fillText(v,ox-15,y(v)+3);}
g.save();g.beginPath();g.rect(ox,oy,scale*(bounds[1]-bounds[0]),scale*(bounds[3]-bounds[2]));g.clip();
g.strokeStyle='#233f4c';g.lineWidth=3;g.strokeRect(x(0),y(20),20*scale,20*scale);
for(const r of D.world.repairs){g.fillStyle=colors.teal;g.fillRect(x(r[0]),y(r[3]),(r[1]-r[0])*scale,(r[3]-r[2])*scale);}
const mover=D.movers[floorTime(D.movers,s.time)],r=mover.rect;g.fillStyle='#7b8d98';g.fillRect(x(r[0]),y(r[3]),(r[1]-r[0])*scale,(r[3]-r[2])*scale);g.fillStyle='#233f4c';if(id==='arena')g.fillText('mover',x((r[0]+r[1])/2),y(r[3]) -7);
D.world.sources.forEach((p,i)=>{g.beginPath();g.arc(x(p[0]),y(p[1]),D.world.sourceRadius*scale,0,Math.PI*2);g.fillStyle=i===0?'#f9dfc6':'#dfe7e9';g.fill();g.lineWidth=i===0?2.5:1;g.strokeStyle=i===0?colors.orange:'#718995';g.stroke();g.fillStyle=i===0?colors.orange:'#405865';g.fillText(i===0?'S0':String(i),x(p[0]),y(p[1])+4);});
g.beginPath();for(let i=0;i<=index;i++){const p=F[i].position;i===0?g.moveTo(x(p[0]),y(p[1])):g.lineTo(x(p[0]),y(p[1]));}if(s.e)g.lineTo(x(s.position[0]),y(s.position[1]));g.strokeStyle=colors.blue;g.lineWidth=2;g.stroke();
const bx=x(s.position[0]),by=y(s.position[1]),radius=D.world.bodyRadius*scale;g.beginPath();g.arc(bx,by,radius,0,Math.PI*2);g.fillStyle='#cce6f2';g.fill();g.strokeStyle=s.contact?colors.orange:colors.blue;g.lineWidth=s.contact?3:2;g.stroke();g.beginPath();g.moveTo(bx,by);g.lineTo(bx+Math.cos(s.angle)*radius,by-Math.sin(s.angle)*radius);g.strokeStyle='#123b50';g.lineWidth=2;g.stroke();g.restore();}
function range(s){switch($('focus').value){case'impact':return [5.8,8];case'selection':return [Math.max(0,s.time-1),Math.min(F.at(-1).time,s.time+1)];case'last':return [F.at(-1).time-10,F.at(-1).time];default:return [0,F.at(-1).time];}}
function plot(id,series,limits,time,reference=[]){const [g,w,h]=setup($(id)),left=57,right=12,top=14,bottom=28;const [t0,t1]=limits;let vals=[];for(const s of series)for(const [t,v] of s.points)if(t>=t0&&t<=t1&&v!==null)vals.push(v);for(const r of reference)vals.push(r.value);let low=Math.min(...vals),high=Math.max(...vals);if(!vals.length){low=0;high=1;}let delta=high-low||Math.max(.01,Math.abs(high)*.1);low-=delta*.09;high+=delta*.09;const X=t=>left+(t-t0)/(t1-t0)*(w-left-right),Y=v=>h-bottom-(v-low)/(high-low)*(h-top-bottom);
g.font='11px Segoe UI';g.lineWidth=1;for(let j=0;j<4;j++){const v=low+(high-low)*j/3;g.strokeStyle=colors.grid;g.beginPath();g.moveTo(left,Y(v));g.lineTo(w-right,Y(v));g.stroke();g.fillStyle='#526775';g.textAlign='right';g.fillText(Math.abs(v)<.001&&v!==0?v.toExponential(1):v.toFixed(3),left-7,Y(v)+4);}for(let j=0;j<5;j++){const t=t0+(t1-t0)*j/4;g.fillStyle='#526775';g.textAlign='center';g.fillText(t.toFixed(t1-t0<10?2:1),X(t),h-8);}g.textAlign='right';g.fillText('time / s',w-right,10);
g.save();g.beginPath();g.rect(left,top,w-left-right,h-top-bottom);g.clip();for(const r of reference){g.strokeStyle=r.color||'#8796a1';g.setLineDash(r.dash||[4,4]);g.beginPath();g.moveTo(X(t0),Y(r.value));g.lineTo(X(t1),Y(r.value));g.stroke();}
for(const s of series){g.strokeStyle=s.color;g.lineWidth=1.6;g.setLineDash(s.dash||[]);g.beginPath();let started=false;for(const [t,v] of s.points){if(t<t0||t>t1||v===null){started=false;continue;}if(!started){g.moveTo(X(t),Y(v));started=true;}else g.lineTo(X(t),Y(v));}g.stroke();}
g.setLineDash([2,3]);g.strokeStyle='#19394b';g.lineWidth=1;if(time>=t0&&time<=t1){g.beginPath();g.moveTo(X(time),top);g.lineTo(X(time),h-bottom);g.stroke();}g.restore();}
const full=[0,F.at(-1).time];const series=(key,color,dash)=>({points:F.map(f=>[f.time,typeof key==='function'?key(f):f[key]]),color,dash});
const reserveSeries=[series('E',colors.blue),series('I',colors.purple,[5,3])],stockSeries=[series('stock',colors.orange)],budgetSeries=[series('cumTransfer',colors.blue),series('cumExpense',colors.orange,[5,3]),series(f=>f.E-.7,colors.purple,[2,3])],actuatorSeries=[series(f=>f.commands[0],colors.blue),series(f=>f.commands[1],colors.orange,[5,3]),series(f=>f.forces[0],colors.purple),series(f=>f.forces[1],colors.gray,[5,3])];
const forceSeries=[{points:D.forceEvents.map(r=>[r[0],r[1]]),color:colors.blue}],integritySeries=[{points:[[0,1],...EV.map(e=>[e.time,e.I])],color:colors.purple}];
function windows(s){const [g,w,h]=setup($('windows')),pad=4,x=t=>pad+t/full[1]*(w-2*pad);for(const a of D.windows){g.fillStyle=!a.complete_0_2_second_interval?colors.purple:a.positive_net_contact_interval?colors.blue:a.net_energy_sign==='negative_resolved'?colors.orange:'#b6c1c7';const sx=x(a.start_time),ew=Math.max(.5,x(a.end_time)-sx);g.fillRect(sx,12,ew,28);if(!a.complete_0_2_second_interval){g.strokeStyle='#fff';g.beginPath();g.moveTo(sx,12);g.lineTo(sx+ew,40);g.stroke();}}g.strokeStyle='#102e40';g.lineWidth=2;g.beginPath();g.moveTo(x(s.time),5);g.lineTo(x(s.time),46);g.stroke();g.fillStyle='#526775';g.font='11px Segoe UI';g.fillText('0 s',pad,61);g.textAlign='right';g.fillText('91.83 s',w-pad,61);const a=D.windows.find(a=>s.time>a.start_time&&s.time<=a.end_time+1e-12);$('windowNote').textContent=a?`${fmt(a.start_time,2)}–${fmt(a.end_time,2)} s · ${a.complete_0_2_second_interval?(a.positive_net_contact_interval?'positive-net contact':a.net_energy_sign==='negative_resolved'?(a.source_0_positive_duration_contact?'negative-net contact':'negative-net · no source contact'):'other / '+a.net_energy_sign):'partial tail · administrative pause'} · ΔE ${fmt(a.energy_delta,9)}`:'Initial state · no completed energy window.';}
function panels(s){const f=s.f,e=s.e,source=e||f,own=f.issued===null?null:D.actions[f.issued],latest=D.actions[floorTime(D.actions,s.time)];
$('physicsPanel').innerHTML=table([['Pose timestamp',`${fmt(s.time,10)} s${e?' · event pose':' · native endpoint'}`],['Position',s.position.map(v=>fmt(v)).join(', ')],['Orientation',fmt(s.angle,9)+' rad'],['Native velocity sample',`${fmt(f.time,6)} s · [${f.velocity.map(v=>fmt(v,9)).join(', ')}]`],['Angular velocity',fmt(f.omega,9)],['Delivered commands L / R',f.commands.map(v=>fmt(v,9)).join(' / ')],['Issued owner of this native step',own?`${fmt(own.time,6)} s · [${own.command.map(v=>fmt(v,9)).join(', ')}]`:'No step delivered at t=0'],['Latest recorded issued decision',`${fmt(latest.time,6)} s · [${latest.command.map(v=>fmt(v,9)).join(', ')}]`],['Realized actuator forces L / R',f.forces.map(v=>fmt(v,9)).join(' / ')],['Force sample timestamp',fmt(f.time,6)+' s (native record)'],['Impact impulse',e&&e.impact?fmt(e.contacts.reduce((a,c)=>a+(c.impulse||0),0),12):'Select an impact event to inspect']]);
$('viabilityPanel').innerHTML=table([['Sample scope',e?'Selected physical event':'Selected native step'],['Energy E',fmt(s.E,12)],['Integrity I',fmt(s.I,12)],['Source-0 stock',fmt(s.stock,12)],['Intake in selected event/step',fmt(source.transfer,12)],['Expenditure in event/step',fmt(source.expense,12)],['Net E in event/step',fmt(e?e.E-e.Ebefore:f.deltaE,12)],['E minus initial 0.7',fmt(s.E-.7,12)],['Integrity debit / restoration',`${fmt(source.damage,12)} / ${fmt(source.repair,12)}`]]);
$('accountingPanel').innerHTML=table([['Operand scope',e?`Event ${e.id} at ${fmt(e.time,10)} s`:`Native step ${f.index}, ending ${fmt(f.time,10)} s`],['Source-0 debit',fmt(source.debit,12)],['Body credit, all sources',fmt(source.credit,12)],['Source-0 renewal',fmt(source.renewal,12)],['Credit − all-source transfer',fmt(source.residual,12)],['Transfer',fmt(source.transfer,12)],['Expenditure',fmt(source.expense,12)]]);
$('sensorNote').textContent=`Observer records at native endpoint ${fmt(f.time,6)} s. These 29 raw coordinates are not live input. Held E/I = [${f.heldEI.map(v=>fmt(v,9)).join(', ')}], sampled at ${fmt(f.eiTime,6)} s. ${e?'The exact selected event lies at its own timestamp; no sensor sample is invented there.':''}`;
$('sensorsPanel').innerHTML=table(D.labels.map((k,i)=>[k,fmt(f.raw[i],9)]));
if(e){$('eventPanel').innerHTML=table([['Event ID / kind',`${e.id} · ${e.kind}${e.impact?' · zero-duration impact':''}`],['Recorded end time / duration',`${fmt(e.time,12)} s / ${fmt(e.duration,12)} s`],['Certified contacts',e.contacts.map(c=>c.collider).join(', ')||'none'],['Sustained force',e.force==null?'not recorded for this event':fmt(e.force,12)],['Impact impulse',e.impact?fmt(e.contacts.reduce((a,c)=>a+c.impulse,0),12):'not an impact'],['E before → after',`${fmt(e.Ebefore,12)} → ${fmt(e.E,12)}`],['I before → after',`${fmt(e.Ibefore,12)} → ${fmt(e.I,12)}`],['Integrity debit / restoration',`${fmt(e.damage,12)} / ${fmt(e.repair,12)}`],['Transfer / expenditure',`${fmt(e.transfer,12)} / ${fmt(e.expense,12)}`],['Source debit / body credit',`${fmt(e.debit,12)} / ${fmt(e.credit,12)}`]]);}else $('eventPanel').innerHTML=`<p>Native ${f.index} selected. ${f.eventEnd>f.eventStart?`Its recorded physical events are ${f.eventStart}–${f.eventEnd-1}.`:'No advanced physical event at the initial state.'} Use the event selector or a marker for exact sub-step operands.</p>`;}
function render(){const s=selected();$('scrub').value=index;$('clock').textContent=fmt(s.time,10)+' s';$('sample').textContent=s.e?`event ${eventId} · native sample ${index}`:`native ${index} / 9183`;$('selectionNote').textContent=s.e?'Exact recorded event selected. Pose, E/I and stock use that event; other quantities retain their labelled native or controller timestamps.':`Recorded native endpoint. No interpolation. ${index===9183?'Administrative pause: wall_time_limit. The unobserved 28.17 s are not displayed.':''}`;
$('energy').textContent=fmt(s.E);$('integrity').textContent=fmt(s.I);$('stock').textContent=fmt(s.stock);$('contact').textContent=s.contact?'Certified contact':'No contact';$('force').textContent=s.force==null?(s.e&&s.e.impact?'Impact impulse':'—'):fmt(s.force);
$('poseNote').textContent=`Body pose at ${fmt(s.time,10)} s · x=${fmt(s.position[0])}, y=${fmt(s.position[1])}, angle=${fmt(s.angle,8)} rad.`;const m=D.movers[floorTime(D.movers,s.time)];$('moverNote').textContent=`Mover: actual recorded axis-aligned rectangle from ${fmt(m.time,6)} s; sample age ${fmt(s.time-m.time,6)} s. Latest recorded geometry held visually; no interpolated mover sample.`;
plan('arena',[0,20,0,20],s);plan('closeup',[2,7,1.5,4.5],s);windows(s);plot('forcePlot',forceSeries,range(s),s.time,[{value:.1,dash:[6,4]},{value:.25,dash:[2,3]}]);plot('integrityPlot',integritySeries,range(s),s.time);plot('reservesPlot',reserveSeries,full,s.time);plot('stockPlot',stockSeries,full,s.time);plot('budgetPlot',budgetSeries,full,s.time);plot('actuatorPlot',actuatorSeries,full,s.time);panels(s);document.body.dataset.nativeIndex=index;document.body.dataset.selectedTime=s.time;document.body.dataset.eventId=eventId===null?'':eventId;}
$('play').addEventListener('click',()=>{if(playing){pause();return;}if(index===F.length-1)setNative(0);eventId=null;playing=true;$('play').textContent='Pause records';playOrigin=F[index].time;wallOrigin=performance.now();const tick=now=>{if(!playing)return;const t=playOrigin+(now-wallOrigin)/1000*Number($('speed').value);setNative(floorTime(F,Math.min(t,full[1])),false);if(t>=full[1])pause();else raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);});
$('speed').addEventListener('change',()=>{if(playing){playOrigin=F[index].time;wallOrigin=performance.now();}});$('restart').addEventListener('click',()=>setNative(0));$('step').addEventListener('click',()=>setNative(index+1));$('back').addEventListener('click',()=>setNative(index-1));$('scrub').addEventListener('input',e=>setNative(e.target.value));$('firstContact').addEventListener('click',()=>{$('focus').value='impact';setEvent(D.firstContact);});$('firstPositive').addEventListener('click',()=>{$('focus').value='impact';setNative(D.firstPositive.last_native);});$('peak').addEventListener('click',()=>{$('focus').value='impact';setEvent(D.peakForce[2]);});$('stop').addEventListener('click',()=>{$('focus').value='last';setNative(F.length-1);});$('focus').addEventListener('change',render);
$('eventGo').addEventListener('click',()=>{const n=Number($('eventNumber').value);if(Number.isInteger(n))setEvent(n);});$('eventPrev').addEventListener('click',()=>setEvent((eventId===null?Math.max(0,F[index].eventEnd-1):eventId)-1));$('eventNext').addEventListener('click',()=>setEvent((eventId===null?Math.max(-1,F[index].eventEnd-1):eventId)+1));
for(const m of D.markers){const b=document.createElement('button');b.textContent=`${fmt(m.time,6)} s · ${m.label}`;b.addEventListener('click',()=>{$('focus').value='selection';setEvent(m.event);});$('markers').appendChild(b);}
$('damageNote').textContent=`Ledger totals: impact debit ${fmt(D.impactDamage,12)}; positive-duration contact debit ${fmt(D.sustainedDamage,12)}. These are recorded accounting categories, not an inferred causal model.`;
$('provenance').innerHTML=table(Object.entries(D.provenance))+D.limitations.map(t=>`<p>${esc(t)}</p>`).join('');
window.addEventListener('resize',render);document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>{}));render();
})();
